stages:
  - validate
  - test
  - security
  - build
  - publish
  - gitops

variables:
  APP_PORT: "8080"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  HARBOR_HOST: "harbor.local"
  HARBOR_PROJECT: "platform-lab"
  GITOPS_BRANCH: "deployment_files"

validate:
  stage: validate
  script:
    - echo "Validating application and deployment files"

test:
  stage: test
  script:
    - npm ci
    - npm test

security:
  stage: security
  script:
    - echo "LAB: dependency/SAST/container checks go here"

build-image:
  stage: build
  script:
    - export IMAGE="$HARBOR_HOST/$HARBOR_PROJECT/$APP_NAME:$IMAGE_TAG"
    - echo "Building $IMAGE with Podman/Buildah"
    - podman build -t "$IMAGE" .

publish-image:
  stage: publish
  script:
    - export IMAGE="$HARBOR_HOST/$HARBOR_PROJECT/$APP_NAME:$IMAGE_TAG"
    - echo "$HARBOR_PASSWORD" | podman login "$HARBOR_HOST" -u "$HARBOR_USER" --password-stdin
    - podman push "$IMAGE"

gitops-update:
  stage: gitops
  script:
    - echo "Update deployment_files/environments/ti/values.yaml with image tag $IMAGE_TAG"
    - echo "Argo CD is responsible for reconciliation/deployment to OpenShift"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
